apps/dpnk: fix dpnk.ChoiceTypeAdmin must inherit class error
Error message:

```
AssertionError: dpnk.ChoiceTypeAdmin must inherit from SortableAdminBase since ChoiceInline inherits from SortableInlineAdminMixin.
```