apps/dpnk: fix dpnk.CompetitionAdmin must inherit class error
Error message:

```
AssertionError: dpnk.CompetitionAdmin must inherit from SortableAdminBase since QuestionInline inherits from SortableInlineAdminMixin.
```