apps/dpnk: using f-string string interpolation instead of Django cursor raw params
To remove simple quotes around SQL raw update meterialized view name
query.

From:

```
REFRESH MATERIALIZED VIEW 'view_name';
```

Error message:

```
Traceback (most recent call last):
django.db.utils.ProgrammingError: syntax error at or near "'data_core_reporting'"
LINE 1: REFRESH MATERIALIZED VIEW 'data_core_reporting'
```

To:

```
REFRESH MATERIALIZED VIEW view_name;
```