apps/coupons/models: fix showing CouponSandwich e-email address if e-mail address value is None
Error message:

```
  File ".../smmapdfs/admin_abcs.py", line 43, in recipient
    return ", ".join(obj.get_email())
TypeError: sequence item 0: expected str instance, NoneType found
```