Revert "build(deps): bump pillow in /monorepo/docker-base-image (#315)"
This reverts commit 7f8aa340d2e150a7913836774587771b34751d21.

Downgrade package version as result of an django-avatar py package
error:

```
AttributeError: module 'PIL.Image' has no attribute 'ANTIALIAS'
```