apps/dpnk: fix dpnk.CampaignAdmin must inherit class error
Error message:

```
AssertionError: dpnk.CampaignAdmin must inherit from SortableAdminBase since TShirtSizeInline inherits from SortableInlineAdminMixin
```