apps/dpnk: fix getting has any tshirt value during tests
When PK is not exists.

Fix error:

```
ValueError: 'Campaign' instance needs to have a primary key value before
this relationship can be used.
```

Compatibile with Django 5.2 version.